FROM python:3.8

COPY requirements_worker.txt /requirements.txt
RUN python -m pip install -U pip && \
    python -m pip install -r requirements.txt && \
    python -m pip cache purge

COPY ./worker /worker
WORKDIR /worker

CMD celery -A tasks worker