FROM python:3.8

COPY requirements_api.txt /requirements.txt
RUN python -m pip install -U pip && \
    python -m pip install -r requirements.txt && \
    python -m pip cache purge

COPY ./api /api
WORKDIR /api

CMD uvicorn app:app --host=0.0.0.0 --port=5000